# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.11
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

package Template::Plugin::React::RESimple;
use base qw(Exporter);
use base qw(DynaLoader);
package Template::Plugin::React::RESimplec;
bootstrap Template::Plugin::React::RESimple;
package Template::Plugin::React::RESimple;
@EXPORT = qw();

# ---------- BASE METHODS -------------

package Template::Plugin::React::RESimple;

sub TIEHASH {
    my ($classname,$obj) = @_;
    return bless $obj, $classname;
}

sub CLEAR { }

sub FIRSTKEY { }

sub NEXTKEY { }

sub FETCH {
    my ($self,$field) = @_;
    my $member_func = "swig_${field}_get";
    $self->$member_func();
}

sub STORE {
    my ($self,$field,$newval) = @_;
    my $member_func = "swig_${field}_set";
    $self->$member_func($newval);
}

sub this {
    my $ptr = shift;
    return tied(%$ptr);
}


# ------- FUNCTION WRAPPERS --------

package Template::Plugin::React::RESimple;


############# Class : Template::Plugin::React::RESimple::RESimple ##############

package Template::Plugin::React::RESimple::RESimple;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( Template::Plugin::React::RESimple );
%OWNER = ();
%ITERATORS = ();
sub new {
    my $pkg = shift;
    my $self = Template::Plugin::React::RESimplec::new_RESimple(@_);
    bless $self, $pkg if defined($self);
}

sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        Template::Plugin::React::RESimplec::delete_RESimple($self);
        delete $OWNER{$self};
    }
}

*exec = *Template::Plugin::React::RESimplec::RESimple_exec;
*output = *Template::Plugin::React::RESimplec::RESimple_output;
sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


# ------- VARIABLE STUBS --------

package Template::Plugin::React::RESimple;

1;
